library(sqldf)
cl <- c("character","character", "numeric","numeric","numeric","numeric","numeric","numeric","numeric")
hpcdata <- read.csv.sql("household_power_consumption.txt", sql = "select * from file where Date in ('1/2/2007','2/2/2007')", sep = ";", header = TRUE, colClasses = cl)
hpcdata$datetime <- as.POSIXct(paste(hpcdata$Date, hpcdata$Time), format="%d/%m/%Y %H:%M:%S")
png(filename = "plot4.png")
par(mfrow = c(2,2))
plot(hpcdata$datetime, hpcdata$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
plot(hpcdata$datetime, hpcdata$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(hpcdata$datetime, hpcdata$Sub_metering_1, type = "n", xlab = "", ylab = "Energy sub metering")
lines(hpcdata$datetime, hpcdata$Sub_metering_1, col = "black")
lines(hpcdata$datetime, hpcdata$Sub_metering_2, col = "red")
lines(hpcdata$datetime, hpcdata$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty = c(1,1,1), col = c("black", "red", "blue"), bty = "n")
plot(hpcdata$datetime, hpcdata$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()